config/routes.rb
Rails.application.routes.draw do
  get 'recipes', to: 'recipes#index'
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'

  root 'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = RecipeService.get_entries
  end

  def show
    @recipe = RecipeService.get_details(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        body {
            background-color: #f0ebdc;
        }
    </style>
</head>

<body>
    <div class='container'>
        <%= yield %>
    </div>
</body>

</html>

app/views/recipes/index.html.erb
<h1>Recipes List</h1>
<hr>
<div class='row'>
    <% @recipes.each do |recipe| %>
        <div class='row recipeItem'>
            <div class='col-md-3'>
                <%= image_tag recipe.photo.url, class: 'img-thumbnail card-img' %>
            </div>
            <div class='col-md-8'>
                <div class='card-body'>
                    <%= link_to recipe.title, recipe_path(recipe.id), class: 'card-text' %><br />
                </div>
            </div>
        </div>
    <% end %>
</div>


<style>
    img {
        width: 50%;
    }

    a {
        text-decoration: none;
        color: black;
        font-size: 1.2em;
    }

    a:visited {
        color: black;
    }

    a:hover {
        color: black;
        text-decoration: none;
    }

    hr {
        border:none;
        height: 20px;
        width: 95%;
        height: 50px;
        margin-top: 0;
        border-bottom: 1px solid #1f1209;
        box-shadow: 0 20px 20px -20px #ccc;
        margin: -50px auto 10px; 
    }

    h1 {
        font-family: "Exo";
    }

    .recipeItem {
        margin-bottom: 0.5em;
        background-color: #F8E9D8;
        box-shadow: 0 20px 20px -20px #ccc;
    }
</style>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<div class='photo'>
    <%= image_tag @recipe.photo.url %><br />
</div>
<% if @recipe.methods.include?(:tags) %>
    <% @recipe.tags.each do |tag| %>
        <span class='badge badge-light'><%= tag.name %></span>
    <% end %>
<% end %>
<div class='description'>
    <%= @recipe.description %><br />
</div>
<% if @recipe.methods.include?(:chef)%>
    <div class='chefName'>
        Chef: <%= @recipe.chef.name%>
    </div>
<% end %>

<style>
    h1 {
        font-family: "Exo";
    }

    img {
        box-shadow: 8px 8px 10px #aaa;
        width: 75%;
    }

    .tags {
        margin-bottom: 6%; 
    }

    .description {
        font-size: 1.5em;
    }

    .photo {
        text-align: center;
        margin-bottom: 1em;
    }

    .chefName {
        font-size: 1.5em;
        font-style: italic;
    }
</style>